// ── src/db/client.ts ──────────────────────────────────────────────────────
// Thin wrapper over node:sqlite (built-in, zero-dependency). In production
// this is Supabase/Postgres + Drizzle (Doc 01); the query surface here is
// deliberately small so swapping the driver is mechanical.

import { DatabaseSync } from "node:sqlite";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { randomUUID } from "node:crypto";

// The DB is a runtime artifact (regenerated by `npm run seed`), so it lives in
// local storage rather than the project tree. Override with ADPILOT_DB.
// Note: some network/FUSE-mounted folders can't host SQLite (no file locking),
// which is why we default to the OS temp dir.
const DB_PATH = process.env.ADPILOT_DB ?? join(tmpdir(), "adpilot.db");
const SCHEMA_PATH = join(import.meta.dirname, "schema.sql");

let _db: DatabaseSync | null = null;

export function db(): DatabaseSync {
  if (_db) return _db;
  _db = new DatabaseSync(DB_PATH);
  _db.exec("PRAGMA foreign_keys = ON;");
  _db.exec("PRAGMA busy_timeout = 3000;");
  return _db;
}

/** (Re)create all tables from schema.sql. Idempotent (IF NOT EXISTS). */
export function migrate(): void {
  db().exec(readFileSync(SCHEMA_PATH, "utf8"));
}

/** Drop everything for a clean reseed. */
export function resetSchema(): void {
  const d = db();
  const tables = d
    .prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")
    .all() as { name: string }[];
  d.exec("PRAGMA foreign_keys = OFF;");
  for (const t of tables) d.exec(`DROP TABLE IF EXISTS ${t.name};`);
  d.exec("PRAGMA foreign_keys = ON;");
  migrate();
}

export const newId = (): string => randomUUID();
export const nowIso = (): string => new Date().toISOString();

// Convenience helpers ------------------------------------------------------
export function run(sql: string, params: unknown[] = []): void {
  db().prepare(sql).run(...(params as never[]));
}
export function all<T = Record<string, unknown>>(sql: string, params: unknown[] = []): T[] {
  return db().prepare(sql).all(...(params as never[])) as T[];
}
export function get<T = Record<string, unknown>>(sql: string, params: unknown[] = []): T | undefined {
  return db().prepare(sql).get(...(params as never[])) as T | undefined;
}
